Resources:
  CognitoUserPoolAppUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      # Generate a name based on the stage
      UserPoolName: ${self:service.name}-${self:provider.stage}-user-pool
      # Set email as an alias
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: userType
          Required: false
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: userId
          Required: false
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: placeId
          Required: false
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: termsConditions
          Required: false
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: privacyCookiePolicy
          Required: false
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: referralCode
          Required: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
          TemporaryPasswordValidityDays: 7
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
      LambdaConfig:
        PostConfirmation:
          Fn::Join:
              - ':'
              -
                - 'arn:aws:lambda'
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - 'function'
                - somap-api-${self:provider.stage}-signUp
      EmailConfiguration:
        EmailSendingAccount: DEVELOPER
        From: noreply@somap.app
        ReplyToEmailAddress: somap.business@gmail.com
        SourceArn: arn:aws:ses:us-east-1:031614885447:identity/somap.app
      EmailVerificationSubject: "Verify SoMap Account"
      EmailVerificationMessage: "<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'/><div leftmargin='0' marginwidth='0' topmargin='0' marginheight='0' offset='0'style='height:auto !important;width:100% !important; font-family: 'Montserrat', sans-serif;'> <table style='max-width:600px; background-color:#ffffff;border:1px solid #e4e2e2;border-collapse:separate !important; border-radius:10px;border-spacing:0;color:#242128; margin:auto;padding:40px;' heigth='auto'> <tbody> <tr> <td style='padding-bottom:40px;border-top:0;height:100% !important;width:100% !important;'> <span style='color: #8f8f8f; font-weight: normal; line-height: 2; font-size: 14px;'>Welcome!</strong></span> </td><td style='padding-bottom:40px;border-top:0;height:100% !important;width:100% !important;'> <img src='https://somap.app/assets/logos/mobile.png' style='width: 60px'/> </td></tr><tr> <td colSpan='2' style='padding-top:10px;border-top:1px solid #e4e2e2'> <h3 style='color:#303030; font-size:18px; line-height: 1.6; font-weight:800;'>Almost done!</h3> <p style='color:#8f8f8f; font-size: 14px; padding-bottom: 20px; line-height: 1.4;'> To complete your SoMap sign up, we just need to verify your email address. </p></td></tr><tr> <td colSpan='2'> <table style='min-width:100%;border-collapse:collapse;'> <tbody> <tr> <td style='padding:15px 0px;' valign='top' align='center'> <table style='border-collapse:separate !important;'> <tbody> <tr> <td align='center' valign='middle' style='padding:13px;'> <a href='{####}' title='Verify email' target='_blank' style='font-size: 14px; line-height: 1.5; font-weight: 700; letter-spacing: 1px; padding: 15px 40px; text-align:center; text-decoration:none; color:#FFFFFF; border-radius: 50px; background-color:#F97635;'>Verify email</a> </td></tr></tbody> </table> </td></tr></tbody> </table> </td></tr></tbody> </table></div>"
  CognitoUserPoolAndroidClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn:
      - UserPoolIdentityProviderFacebook
      - UserPoolIdentityProviderGoogle
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:service.name}-${self:provider.stage}-android-client
      UserPoolId:
        Ref: CognitoUserPoolAppUserPool
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - somap:// #TODO CALLBACK LOGIN PER ANDROID
      LogoutURLs:
        - somap:// #TODO CALLBACK LOGOUT PER ANDROID
      SupportedIdentityProviders:
        - COGNITO
        - Facebook
        - Google
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: ${self:service.alias}-${self:provider.stage}-domain
      UserPoolId:
        Ref: CognitoUserPoolAppUserPool
# Print out the Id of the User Pool that is created
Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPoolAppUserPool
  CognitoUserPoolAndroidClientId:
    Value:
      Ref: CognitoUserPoolAndroidClient
