Resources:
  CognitoUserPoolAppUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      # Generate a name based on the stage
      UserPoolName: ${self:service.name}-${self:provider.stage}-user-pool
      # Set email as an alias
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: userType
          Required: false
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: userId
          Required: false
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: placeId
          Required: false
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: termsConditions
          Required: false
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: privacyCookiePolicy
          Required: false
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: referralCode
          Required: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
          TemporaryPasswordValidityDays: 7
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
      LambdaConfig:
        PostConfirmation:
          Fn::Join:
              - ':'
              -
                - 'arn:aws:lambda'
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - 'function'
                - somap-api-${self:provider.stage}-signUp
      EmailConfiguration:
        EmailSendingAccount: DEVELOPER
        From: noreply@somap.app
        ReplyToEmailAddress: somap.business@gmail.com
        SourceArn: arn:aws:ses:us-east-1:031614885447:identity/somap.app
  CognitoUserPoolAndroidClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn:
      - UserPoolIdentityProviderFacebook
      - UserPoolIdentityProviderGoogle
    Properties:
      # Generate an app client name based on the stage
      ClientName: ${self:service.name}-${self:provider.stage}-android-client
      UserPoolId:
        Ref: CognitoUserPoolAppUserPool
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      CallbackURLs:
        - somap:// #TODO CALLBACK LOGIN PER ANDROID
      LogoutURLs:
        - somap:// #TODO CALLBACK LOGOUT PER ANDROID
      SupportedIdentityProviders:
        - COGNITO
        - Facebook
        - Google
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: ${self:service.alias}-${self:provider.stage}-domain
      UserPoolId:
        Ref: CognitoUserPoolAppUserPool
# Print out the Id of the User Pool that is created
Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPoolAppUserPool
  CognitoUserPoolAndroidClientId:
    Value:
      Ref: CognitoUserPoolAndroidClient
